### ISSUE TITLE
Visit durations of 0

### ISSUE THREAD

**Issue by johannes-titz** [StoneStepsInc/StoneStepsWebalizer#16]
Love your fork! :heart: 

Quick question regarding visit duration: If somebody just goes to a single page of a website (just one log entry), will this result in a duration of 0? I get a lot of 0 duration entries, so I thought I should filter them out, but I am not entirely sure what 0 means in this case.

**Comment by StoneStepsInc** [comment]
Thank you. 

Yes, single hit should result in a visit duration being zero, as it simply records the time between first and last requests in a visit. 

In terms of filtering them out, as in removing from the stats with all counters being adjusted, like request counts, transfer size, etc, would be difficult, as it would require going through all aggregates and subtract what was added earlier.

Hiding it in reports could be done for individual hosts, but the numbers for hosts wouldn't reconcile with combined values for countries, ASN numbers, etc. In other words, if there was a single request in the entire log and the host was hidden in the hosts report, that report would be empty, but other reports, like countries, would show activity.

I will also note that you may want to see how your `Cache-Control` is set up for pages and if it doesn't have `max-age` and `must-revalidate`, browsers will avoid sending requests altogether. Good for network traffic, but logs will not capture some of the activity the user could see in the browser.

In the past, there would be accompanying requests (e.g. images, etc), which would contribute into a visit length being non-zero, however small that value might be. I suppose, if the goal for this not to actually get rid of the single-request visits, but make them more natural-looking, one approach for this could be to have a setting for a minimum visit time, such as a few seconds, so a zero could be reported for errors, etc, and a minimum could be reported for successful pages, on the assumption that a person would spend a couple of seconds scanning the page to see if it's useful.

**Comment by johannes-titz** [comment]
Thank you very much for the detailed answer! I guess there is no optimal solution, but it is good to know that a value of 0 might be misleading. My initial idea for filtering them out was that these might be bots, but as per your explanation this will usually not be the case. The visit duration is quite interesting to analyze and a great advantage over the normal webalizer. One just has to keep in mind that the durations might be underestimated.

**Comment by StoneStepsInc** [comment]
I was thinking about this and the only usable option without some support from website apps (e.g. open page beacon of sorts), is to set a minimum visit length for successful requests, which is what I did. 

There's a new option `MinVisitLength`, which is used as a visit length if the visit is zero length and has a successful page or a file request and the user is a human (i.e. non-robot and non-spammer).

There's no released build at this point, so you can either build it yourself or pick up one of the CI builds here. Azure DevOps is capricious for public access and may report access denied for no reason. The triple dots on the right should allow to download packages.

https://dev.azure.com/StoneSteps/Stone%20Steps%20Webalizer/_build/results?buildId=126&view=artifacts&pathAsName=false&type=publishedArtifacts

If you do end up downloading one of these, keep in mind that it's not a released version, so some other change may end up being released as v6.3.0 later, so keep track of the build number, so you can tell them apart.

**Comment by StoneStepsInc** [comment]
I ended up releasing v6.3.0, so disregard the link above if you need binaries. 

I'm closing this issue, as there's not much else that can be done in this app. Let me know if you have questions or feedback.
