### ISSUE TITLE
GeoIP not usable without DNSCache

### ISSUE THREAD

**Issue by magoerlich** [StoneStepsInc/StoneStepsWebalizer#17]
Hi there,

[according to the README](https://github.com/StoneStepsInc/StoneStepsWebalizer/blob/master/README.md?plain=1#L892) it should be possible to disable DNS lookup, without disabling GeoIP by having ```DNSChildren > 0```, ```DNSCache = null``` and ```GeoIPDBPath != null```

But when we configure it like that:
![image](https://github.com/StoneStepsInc/StoneStepsWebalizer/assets/111066683/d64f1d1f-067d-4c8a-9a21-95f9484577b9)

Webalizer complains that he couldn't setup DNS. Is this a bug or did we misinterpreted the configuration options?

It would be really handy to have this working as expected, since we're using GeoIP to identify our users by team/project/office location but we're not interested in the DNS resolving (we dont need ip->hostname) and disabling it will speed up report generation significantly.

Thank you very much.

**Comment by StoneStepsInc** [comment]
This functionality grew organically over the years and, perhaps, could be structured/documented better. 

You can disable DNS look-ups by setting `DNSLookups` to `no`. This will keep just GeoIP functionality working. If `DNSCache` is specified, it will keep track of spammers. I think it can be disabled and only GeoIP will be queried, but I didn't verify it - it's been a while I touched that code. Try it, see if it works. If not, let me know and I'll have a closer look.

**Comment by magoerlich** [comment]
Thank you!
Somehow i missed that configuration option.

This works as we expected:
```
GeoIPCity    yes
GeoIPDBPath  .\internal.mmdb
DNSChildren  1
#DNSCache    cache.dns
DNSLookup    no
```
Querying the ```internal.mmdb``` for location data while not doing any DNS lookups.
