### ISSUE TITLE
HTMLTail inserted twice

### ISSUE THREAD

**Issue by IzzySoft** [StoneStepsInc/StoneStepsWebalizer#8]
Ah, you forgot to tell me there are new releases and where to find them – so I just found them here yesterday, and am now preparing the Debian packages.

Upgrading step-by-step, I just switched from 4.3.6 to 5.0.1 and noticed the image I included with `HTMLTail` now appears twice (it's inserted twice-in-a-row, i.e. one immediately following the other, directly before the `<!-- Page Footer -->`.

```html
<A HREF="https://www.linux.com/"><IMG STYLE="border:0;" SRC="/shared/images/msfree.png" ALT="100% Micro$oft free!"></A><A HREF="https://www.linux.com/"><IMG STYLE="border:0;" SRC="/shared/images/msfree.png" ALT="100% Micro$oft free!"></A>
```

I've checked my config to make sure: `HTMLTail` is only defined once:

```
HTMLTail <A HREF="https://www.linux.com/"><IMG STYLE="border:0;" SRC="/shared/images/msfree.png" ALT="100% Micro$oft free!"></A>
```

Any clue? Though being more a "cosmetic" thing (and I probably could work around that using CSS), it confuses me a bit :zany_face:

Being on it: You might wish to "upgrade" the link in the footer to `https://` :wink:

I'll probably give v5.0.1 a few runs before going on to v6.0.0, then releasing both `.deb` files via my repo as before – so you can point to that again for easy install on Debian based systems. According to the Readme it looks like v6.1.0 is due shortly; give me a ping then please so I can pick it up as well (hopefully with its tail de-duplicated :smile:)

While on it: HTMLValidator complains about the "incomplete" DocType:

```html
<!DOCTYPE HTML>
```

Shouldn't that rather be

```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
```

(just guessing rawly by the formatting I see)?

**Comment by StoneStepsInc** [comment]
Thanks for reporting the double image link. I'll have a look in the next few days.

For a package file, have a look at the install/uninstall scripts I added into the trunk (`master`) recently - see if it makes sense to keep directories in sync.

Regarding `DOCTYPE`, the one it uses now is HTML5 syntax:

https://www.w3.org/QA/2002/04/valid-dtd-list.html
https://html.spec.whatwg.org/#the-doctype

With regards to v6.1.0, it seems that the interest to the project has died down, so I wasn't planning on a new release, but I did set up automated builds, so it's available for anyone who wants to give it a try, but with the understanding that it hasn't been tested as much as before.

The most notable change in v6.0 is the Top ASN report and addition of ASN information into the hosts report. I find it useful in my stats. Although, I did take a bit of a shortcut and implemented it in a way similar to the cities report - without the all-items page. I always hated the pre-formatted all-items pages because they format horribly with international characters, but my attempt to make them into expandable sections didn't work out, so there's no drill-down into these. Just keep in mind.

**Comment by IzzySoft** [comment]
Wow – that was fast! Thanks for looking into the double-image issue (which I hereby confirm still to exist with v6.0.0).

For the package: I still have the SPEC set up here. So all I have to do is to "untar" the archive to a specific location and run my packager (like `relman webalizer 6.0.0` to create the `.deb` for v6.0.0 , upload it to my server and refresh the repo).

Regarding `DOCTYPE`: now you write it's HTML5 I vaguely recall the validator I use might not handle that correctly. The references you gave confirm it's fine, so consider this "done" – apologies for the noise!

I've just published the `.deb` for v5.0.1 (my repo still had v4.3.6 as newest). With publishing v6 I'll wait until my PR is clarified, as I think it's a good idea to have the descriptions in the `sample.conf` matching reality (though that could also be released with the version that has the double-image issue fixed if you prefer, and I push the v6.0.0 `.deb` right away). I saw your comment already and will reply there soon.

Sad to read interest seems to have died down; are folks switching to "big data (collectors)" instead? When asked by like-minded privacy proponents, I always point to Webalizer. Now that newer versions are available, I'll do that even more. Hopefully, that shortly after Easter, maybe a resurrection is possible? :smile:

As for ASN: if time permits, I'll see if I play with that a bit as well, sounds interesting.

**Comment by StoneStepsInc** [comment]
For `HTMLTail`, I cannot seem to reproduce it. Are you sure it's not in one of the included files? All instances will be dumped one after another, in the order it reads them in all configuration files. If you are sure it's not the case, would you mind sending your configuration to support@stonesteps.ca?

I think many switched to tools like Google Analytics. Webalizer reports use really dated static HTML. I changed it to CSS years ago, but it's still a fairly heavy single-page output with those hard to navigate huge all-items pre-formatted pages. No filtering, no searches - things people really expect from modern web apps. At some point I tried to move it to XML/XSL reports, so people can write their own report structure, but that didn't pick up - XSL is quite hard to use. What Webalizer really needs is a complete overhaul of the reporting system, such that the tool generates just data, not HTML, and the web app part of the tool provides an interface to slice and dice this data as much as browser memory allows or even put it into something like Mongo DB and have a Node app go at it.

Anyway, I digress. Let's try to figure out that double image thing first.

**Comment by IzzySoft** [comment]
> For HTMLTail, I cannot seem to reproduce it. Are you sure it's not in one of the included files?

Andre, I'm sure it's in exactly one of the included files – and only in one, nowhere else. I didn't change the configuration when I upgraded from 4.3.6 to 5.0.1, and up to 4.3.6 I didn't have that issue. I'll send a mail with the config and how SSW is called, hopefully that helps clarifying.

> No filtering, no searches - things people really expect from modern web apps.

For me, privacy of my users is more important than convenience of 3rd party services. If I need to search/filter (which I sometimes do), I use GoAccess. Happens not that often. But those two give me all the insights I need. Maybe I'm not the typical site admin. I don't have monetary goals with my sites…

> such that the tool generates just data, not HTML

That's already possible using TSV dumps and feeding them to a database. But that would mean site admins need to write their own logic to evaluate the data.

> and have a Node app go at it.

Thanks – but no(de) :rofl:

> Let's try to figure out that double image thing first.

Yupp. Before we get carried away. I'll prepare the mail for you.

**Comment by StoneStepsInc** [comment]
Ran against your configuration and I'm still not seeing `HTMLtail` inserted twice. Can you post generated HTML (without any identifying bits, like this)? Want to see if there are any hints in the generated HTML structure.
```html
</tbody>
</table>
<A HREF="https://www.linux.com/"><IMG STYLE="border:0;" SRC="/shared/images/msfree.png" ALT="100% Micro$oft free!"></A>
<!-- Page Footer -->
<div class="page_footer_div">
<a href="http://www.stonesteps.ca/webalizer">Stone Steps Webalizer</a> (v5.0.1.4)
</div>
```
Also, I ran my tests against just two of your configuration files, not in the loop, like you do. Can you confirm that you are seeing the double image with all generated reports? If not, email me what specific configuration file you are seeing this with.

**Comment by IzzySoft** [comment]
```html
<tr class="table_footer_tr"><th colspan="5">Totals</th>
<td>541410</td>
<td data-xfer="522879724284">487&nbsp;GB</td>
<td>1423393</td>
<td>3268629</td>
<td>12925753</td>
<td>13859420</td></tr>
</tbody>
</table>
<A HREF="https://www.linux.com/"><IMG STYLE="border:0;" SRC="/shared/images/msfree.png" ALT="100% Micro$oft free!"></A><A HREF="https://www.linux.com/"><IMG STYLE="border:0;" SRC="/shared/images/msfree.png" ALT="100% Micro$oft free!"></A>
<!-- Page Footer -->
<div class="page_footer_div">
<a href="http://www.stonesteps.ca/webalizer">Stone Steps Webalizer</a> (v6.0.0.7)
</div>
```

And after checking all reports I can confirm duplication takes place for all of them, yes. I can give you access to the full reports if you need, just let me know.

Just out of curiosity: what version and platform you run them on? In my case it's the Debian 64bit version, v5.0.1 as well as v6.0.0. Should you have a newer build you use e.g. in a VM and cannot reproduce it with, I gladly give that one a try. Oh, and the Debian running on my stats machine is still Debian 9 (stretch) – waiting to be updated if my provider finally does it…

**Comment by StoneStepsInc** [comment]
The OS shouldn't have any effect on this behavior, but I ran my tests on Debian 9 and Windows with SSW v5.0.1 and v6.0.0.

This output seems to indicate that `HTMLTail` is added twice because, unlike other HTML constructs, this one doesn't add an LF after it, so there's no empty line before `DOCTYPE` and that's how those two appear.

Can you run it manually and check that no configuration file is mentioned more than once in lines prefixed with `Processed configuration file` in the console output? Wonder if one of them somehow is picked up twice.

**Comment by StoneStepsInc** [comment]
Ignore the bit about `HTMLTail` being before `DOCTYPE` - I had `HTMLPre` on my mind and mistyped. Will edit to strike it through shortly. Cannot remember why I didn't output LF after `HTMLTail` at this point. Seems like it would be helpful here.

**Comment by IzzySoft** [comment]
Confirmed:

```
Processed configuration file /etc/webalizer/site_android.conf
Processed configuration file /etc/webalizer/webalizer.conf
Processed configuration file /etc/webalizer/sitewide.conf
Processed configuration file /etc/webalizer/download.conf
Processed configuration file /etc/webalizer/logfile.conf
Processed configuration file /etc/webalizer/dns.conf
Processed configuration file /etc/webalizer/agents.conf
Processed configuration file /etc/webalizer/referer.conf
Processed configuration file /etc/webalizer/search.conf
Processed configuration file /etc/webalizer/spamprot.conf
Processed configuration file /etc/webalizer/htmlformat.conf
```

Though I cannot follow your lines about LF and `DOCTYPE`. A funny thing happens if I add a second `HTMLTail` line right after the first (`HTMLTail <!-- test -->` in my case). In the resulting HTML it was simply appended to the first, but the output to STDOUT changed:

```
Processed configuration file /etc/webalizer/webalizer.conf
Processed configuration file /etc/webalizer/sitewide.conf
Processed configuration file /etc/webalizer/download.conf
Processed configuration file /etc/webalizer/logfile.conf
Processed configuration file /etc/webalizer/dns.conf
Processed configuration file /etc/webalizer/agents.conf
Processed configuration file /etc/webalizer/referer.conf
Processed configuration file /etc/webalizer/search.conf
Processed configuration file /etc/webalizer/spamprot.conf
Processed configuration file /etc/webalizer/htmlformat.conf
Processed configuration file /etc/webalizer/site_android.conf
Processed configuration file /etc/webalizer/webalizer.conf
Processed configuration file /etc/webalizer/sitewide.conf
Processed configuration file /etc/webalizer/download.conf
Processed configuration file /etc/webalizer/logfile.conf
Processed configuration file /etc/webalizer/dns.conf
Processed configuration file /etc/webalizer/agents.conf
Processed configuration file /etc/webalizer/referer.conf
Processed configuration file /etc/webalizer/search.conf
Processed configuration file /etc/webalizer/spamprot.conf
Processed configuration file /etc/webalizer/htmlformat.conf
```

Now what's not funny: even after removing that extra line, the double-processing remains? Looking up previous manual runs I've done, I see the same double-listing frequently. I've cross-checked once more (`grep -i include *`) that there are no double-includes, could not find any.

**Comment by StoneStepsInc** [comment]
My mistake about `DOCTYPE` - added a comment just above yours to clarify.

Content of any of those HTML configuration parameters is just dumped into the HTML, so that extra `<!-- test -->` wouldn't change how files are included. Must be something else.

**Comment by StoneStepsInc** [comment]
Here's the odd pattern that may point in the right direction - in the first case `site_android.conf` is listed first and in the second case `webalizer.conf` is listed first and it seems that when `site_android.conf` is listed, it handles its own includes. Any chance one of the cron jobs is missing `-c` and just picks up `webalizer.conf` by default?

**Comment by IzzySoft** [comment]
I just tried something else: I concatenated all the files to a big `zz.conf`, made sure it did contain no more includes, and used that instead:

```
Processed configuration file /etc/webalizer/webalizer.conf
Processed configuration file /etc/webalizer/sitewide.conf
Processed configuration file /etc/webalizer/download.conf
Processed configuration file /etc/webalizer/logfile.conf
Processed configuration file /etc/webalizer/dns.conf
Processed configuration file /etc/webalizer/agents.conf
Processed configuration file /etc/webalizer/referer.conf
Processed configuration file /etc/webalizer/search.conf
Processed configuration file /etc/webalizer/spamprot.conf
Processed configuration file /etc/webalizer/htmlformat.conf
Processed configuration file /etc/webalizer/zz.conf
```

Could it be that for whatever reason, and other than the docs state, the config file passed by `-c` is used **in addition to** any `webalizer.conf` found? Bingo: Renaming `webalizer.conf` to `webalizer.con` and running with the "full config" again, `HTMLTail` is inserted exactly one time, and output looks like this:

```
Processed configuration file /etc/webalizer/zz.conf
```

**Comment by StoneStepsInc** [comment]
I'm running the same configuration, though and it works as expected. It also seems that in the first output you posted it worked as well and it was before you experimented with concatenation. What was different then?

**Comment by StoneStepsInc** [comment]
It appears that this is the change that is affecting it:

https://bitbucket.org/StoneStepsInc/stonestepswebalizer/issues/8/provide-a-way-to-prioritize-log-file-names

Code change: #bc497d4

Not sure why is it not picking it up in my configuration. Hang on. Will look into this and post later.

**Comment by StoneStepsInc** [comment]
Ok, I know what's going on. In your email you described configuration in `/etc/webalizer/`, so in my tests I put all configuration files there, so there's no `/etc/webalizer.conf`. As soon as I copy `webalizer.conf` into `/etc`, I can see log files included twice because of that change in behavior.

In general, `/etc/webalizer.conf` should just supply some base configuration that can be overwritten in included configuration files. So, you would need to restructure includes such that the default `webalizer.conf` is not included explicitly because it is always included from `/etc`, if present. Otherwise you can just delete it from `/etc` and use it from where you describe it in the email - `/etc/webalizer/webalizer.conf`, in which case the name doesn't matter, really.

**Comment by IzzySoft** [comment]
> Ok, I know what's going on. In your email you described configuration in `/etc/webalizer/`, so in my tests I put all configuration files there, so there's no `/etc/webalizer.conf`.

Correct – same setup here.

> As soon as I copy `webalizer.conf` into `/etc`,

I didn't do that, and there is no `/etc/webalizer.conf` here. As described, all config files reside inside `/etc/webalizer/`.

I've scrolled back the history of my terminal window to the very top: the only time files were **not** included twice was when I explicitly checked for that (Murphy's law). The second time was when I renamed `/etc/webalizer/webalizer.conf` to `/etc/webalizer/webalizer.con`. So I guess when I rename it to anything but `webalizer.conf` (i.e. there is no `webalizer.conf` file at all) it should be fine.

Confirmed: renamed `/etc/webalizer/webalizer.conf` to `/etc/webalizer/webalizer_global.conf`, adjusted the `Include` in the `site_*.conf` files accordingly – no more double inclusion, no duplicated `HTMLTail` anymore. Confirmed for all sites.

So for me the issue is solved this way. Still strange you couldn't reproduce it 1:1. Nevertheless, documentation should be adjusted. Current Readme, emphasis mine:

> * `-c file`
> 
> This option specifies a configuration file to use. Configuration files allow greater control over how The Webalizer behaves, and there are several ways to use them. **If a configuration file is specified with this option, the default configuration file will not be processed.**

The bold part definitely seems to be wrong. Even by what you report, this would rather be "the default configuration file **will be processed first**." So if this is intended, the Readme should be adjusted – otherwise the behavior :wink:

Thanks for your help once more!

**Comment by StoneStepsInc** [comment]
> I didn't do that, and there is no /etc/webalizer.conf here. As described, all config files reside inside /etc/webalizer/.

It searches for the default configuration file in a few places, which for Linux includes current directory, `/etc` (or whatever was defined in `Makefile` and in the directory where the executable is (this is for deployments where all files are in one directory). If it's not one of those cases, then there's some other condition. This behavior cannot be intermittent. 

My guess would be that you changed current directory when running tests and in some cases it picked up `webalizer.conf` from the current direcctory (e.g. if it was `/etc/webalizer`). Other times you ran it from somewhere else and it processed it as it should.

Yes, I'm aware of `README.md` and changing it as we speak. There's a lot of ground to cover there, as configuration is referenced in a bunch of places.

**Comment by StoneStepsInc** [comment]
> PS: Funny that the Bitbucket issue you referenced has the same number (8) as this one here

Indeed, quite a coincidence :)

**Comment by IzzySoft** [comment]
> which for Linux includes current directory

Ouch. You just found it. I was inside the config dir playing with the settings – **except for that "Murphy run".** Good it was just that! Nevertheless, I'll leave that file renamed to prevent such things in the future :rofl:

It also does explain why duplication of `HTMLTail` happened before: the script called by cron first `cd`s to the config dir. The first cron-based run after renaming the file meanwhile happened, confirming the issue solved.

The only thing it does **not** explain is why this didn't happen before v5.0.x.

However: Shall I open another PR to correct the Readme description for `-c file` – as obviously that doesn't reflect reality? Or will you adjust reality to match the Readme instead?

**Comment by StoneStepsInc** [comment]
Yes, go ahead and close it or I can close it later. 

`README.md` changes are being done under a bug in Azure DevOps. I use GitHub only for reporting issues, so issues here last only as long as it takes to figure out what's going on.

Thanks for finding this documentation discrepancy.

**Comment by IzzySoft** [comment]
> I use GitHub only for reporting issues, so issues here last only as long as it takes to figure out what's going on.

Ah! And there I was wondering what happened to issues 1-7. Though at times it's good to have old issues to check with, even if they are solved.

> Thanks for finding this documentation discrepancy.

Thanks for correcting :smiley:

**Comment by StoneStepsInc** [comment]
> Ah! And there I was wondering what happened to issues 1-7

I never delete actual issues. 1-7 were just used for testing. Issues are different from tracking development progress, even on GitHub - you can create a project here and link issues to project cards, which can move through agile stages. I just don't use GitHub projects and use Azure DevOps instead because it's more versatile than GitHub projects and integrate better with build pipelines.

**Comment by IzzySoft** [comment]
I was using Github for many years, but meanwhile moved most of my projects to [Codeberg](https://codeberg.org/) – which itself is FOSS and community-driven. I know and fully trust the team running the platform, so the move included personal reasons as well :wink:
